import Head from 'next/head'


export default function ConnexPage() {
  return (
    <div >
      <Head>
        <title>Connex Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      </main>
    </div>
  )
}
