import Head from 'next/head'




export default function LoginPage() {
  return (
    <div >
      <Head>
        <title>AuthPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      </main>
    </div>
  )
}
