import Head from 'next/head'
import { HomeProvider } from '../src/web_services/info_store/pages/HomePage/context/homeProvider';
import { HomePage } from '../src/web_services/info_store/pages/HomePage';


export default function Home() {
  return (
    <HomeProvider>


      <div >
        <Head>
          <title>Index Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <HomePage />

        </main>
      </div>
    </HomeProvider>
  )
}
