import { Button, Container } from '@mui/material'
import Head from 'next/head'
import { User } from '../src/domain/models/user_model';
import UserUseCases from '../src/domain/usecases/user_usecases';
import { UserCard } from '../src/components/UserCard';
import { ApiResponse, useFetch, useFetch2 } from '../src/hooks/useFetch';


export default function Home() {

  const userUseCases = new UserUseCases();
  const { data, error, loading, getAPIData }: ApiResponse = useFetch2(()=>userUseCases.getAllUsers());

  const fetchData = async () => {
    await getAPIData();
  }



  return (
    <div >
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Container>
          <Button
            variant='contained'
            onClick={fetchData}
          >
            Get users
          </Button>

          {loading && <div> Cargando...</div>}
          {error && error.name === 'UnexpectedError' ? <div>Ha ocurrido un error</div> : ''}
          {/* {!loading && <h2>{'Status code: ' + status.toString()}</h2>} */}

          {data && <div>
            {data.map((user: User) => <UserCard key={user.id} user={user} />)}
          </div>
          }
        </Container>

      </main>
    </div>
  )
}
