import Head from 'next/head'
import { HomeVerumProvider } from '../../src/web_services/verum/pages/context/homeVerumProvider'
import { HomePageVerum } from '../../src/web_services/verum/pages/HomePageVerum'



export default function VerumPage() {
  return (
    <HomeVerumProvider>
      <div >
        <Head>
          <title>Verum Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <HomePageVerum />
        </main>
      </div>
    </HomeVerumProvider>

  )
}
